### ISSUE TITLE
Jigsaw data for ParaGeDi

### ISSUE THREAD

**Issue by mianzhang** [s-nlp/detox#1]
Hi Authors, 

Is the filtered jigsaw data for training ParaGeDi available? I've not found it.

Best

**Comment by avidale** [comment]
The data that we used for training of the classifier and the conditional language model is in https://github.com/s-nlp/detox/tree/main/emnlp2021/data , in the train, dev, and test folders.

**Comment by mianzhang** [comment]
thx.
