### ISSUE TITLE
In file "gedi_inference.ipynb" throws AttributeError: 'GediAdapter' object has no attribute 'forward'

### ISSUE THREAD

**Issue by naman632** [s-nlp/detox#2]
```result = dadapter.generate(inputs, do_sample=True, num_return_sequences=3, temperature=1.0, repetition_penalty=3.0, num_beams=1) ```

This line is throwing the error. Could you please resolve the issue?

**Comment by avidale** [comment]
Hi @naman632 , 
My best gues is that the error is due to the mismatch of the version of the `transformers` package. 
What is the error and what are the versions of Python and transformers that you are using?

**Comment by avidale** [comment]
I've tried to my own code with fresh `transformers==4.24.0`, and it indeed produced an error, until I added the following commit: https://github.com/s-nlp/detox/commit/88cbbc94d346217ad1b8888c839e069f3aa2aca1. 

Now the code should work properly. @naman632, please test it.
