### ISSUE TITLE
GPU specs and time

### ISSUE THREAD

**Issue by martinigoyanes** [s-nlp/detox#4]
Could you please share the specs of the hardware you used to train and do inferenence of ParaGeDi model? I am trying to replicate it while connecting to a cluster of GPUs and I keep getting Out Of Memory errors.

**Comment by avidale** [comment]
I didn't record the exact hardware configuration, and I don't have access to it now. 
But as far as I can remember, all training was done on a single GPU with 8 GB of memory.

**Comment by martinigoyanes** [comment]
That is impressive, I am getting Out Of Memory errors when running on 1 GPU with 12GB of memory. 
I have to limit myself to use bath_size of 4 and it takes more than 12 hours to complete 1 epoch of training. This is how I am running training.

```
N_EPOCHS=2 # default
TOKENIZER_NAME=ceshine/t5-paraphrase-paws-msrp-opinosis # default
MAX_SEQUENCE_LEN=128 # default
BATCH_SIZE=4 # default=8
LOGGING_STEPS=100
SAVING_STEPS=2000

mkdir -p "${JOB_PATH}/model"
mkdir -p "${JOB_PATH}/logs"

export TRANSFORMERS_OFFLINE=1 # the node in the cluster has no internet connection, I have to pre-download models
python emnlp2021/style_transfer/paraGeDi/gedi_training/gedi_training.py \
--tokenizer_name $TOKENIZER_NAME \
--data_dir $DATA_PATH \
--working_dir "${JOB_PATH}/model" \
--log_dir "${JOB_PATH}/logs" \
--n_epochs $N_EPOCHS \
--max_seq_length $MAX_SEQUENCE_LEN \
--train_batch_size $BATCH_SIZE \
--eval_batch_size $BATCH_SIZE \
--logging_steps $LOGGING_STEPS \
--saving_steps $SAVING_STEPS \
--tensorboard
```

Do you know why might I be getting such bad performance? (Even for inference I also get Out Of Memory errors)
