### ISSUE TITLE
Regular paraphraser

### ISSUE THREAD

**Issue by martinigoyanes** [s-nlp/detox#5]
On your paper you comment "For ParaGeDi, we use a pre-trained T5-based (Raffel et al., 2020) paraphraser, fine-tuned on a **random subsample of the ParaNMT dataset** (Wieting and Gimpel, 2018)"  

You also link this mentioned mode to [https://huggingface.co/ceshine/t5-paraphrase-paws-msrp-opinosis](https://huggingface.co/ceshine/t5-paraphrase-paws-msrp-opinosis) . On the repo for this linked model it says "A pre-trained model trained on both PAWS and Quora datasets".

So, is the T5 paraphrase you employ for ParaGeDi fine-tuned on a random subsample of ParaNMT dataset or on PAWS and Quora datasets?

**Comment by avidale** [comment]
Hi Martin!
The fine-tuning was done sequentially. 
I took the model `ceshine/t5-paraphrase-paws-msrp-opinosis`, which is T5-base fine-tuned on PAWS and Quora, and I further fine-tuned it on ParaNMT.

**Comment by martinigoyanes** [comment]
Great thanks ! 
Could you share the random subsample of data you used from ParaNMT (as you mention in the paper) to train such  model? 
Or at least how was that subsample gathered? 
Maybe, its even possible that you have that fine-tuned model and you could share it? 

Thank you so much!

**Comment by avidale** [comment]
Yes, the fine-tuned model is https://huggingface.co/s-nlp/t5-paraphrase-paws-msrp-opinosis-paranmt, feel free to reuse it.

**Comment by martinigoyanes** [comment]
Thank you so much for such a fast reply. I am a bit confused I thought that was the fine-tuned model on the mined ParaNMT corpus.

The paper reads:
```
We then compare the regular paraphraser from Sec-
tion 5.4 fine-tuned on a random subset of ParaNMT
(**regular**) with its version fine-tuned on the mined
toxic/safe parallel paraphrase corpus (**mined**). We
also plug both paraphrasers into ParaGeDi model
and compare the overall performance.
```

Therefore, I was trying to get access to both. Correct me if I am wrong then:
- **Regular** -> [https://huggingface.co/s-nlp/t5-paraphrase-paws-msrp-opinosis-paranmt](https://huggingface.co/s-nlp/t5-paraphrase-paws-msrp-opinosis-paranmt)
- **Mined** -> Not available (could it be released?)

**Comment by avidale** [comment]
* **Mined** -> https://huggingface.co/s-nlp/t5-paranmt-detox
(this link exists in the README in the repository root)

The link to the "regular" version, https://huggingface.co/s-nlp/t5-paraphrase-paws-msrp-opinosis-paranmt, could have been found in the notebook with the inference example (https://github.com/s-nlp/detox/blob/main/emnlp2021/style_transfer/paraGeDi/gedi_inference.ipynb), adjusted to the repository rename `SkolkovoInstitute ->s-nlp`.

**Comment by avidale** [comment]
Anyway, for detoxification of English text, I don't recommend the unsupervised ParaGeDi approach. 
Instead, you can use a supervised model, such as https://huggingface.co/s-nlp/bart-base-detox, trained on a manually curated detoxification corpus. It is more reliable and has higher human and automatic quality metrics.
