### ISSUE TITLE
Error  while doing evaluation using metric.py 

### ISSUE THREAD

**Issue by bhaveshk1502** [s-nlp/detox#8]
hello, sorry for bothering but I found another error, this is the error posted Screenshot and copy pasted error as well 

![image](https://user-images.githubusercontent.com/81642316/228864679-e891e5b7-f656-4fbb-9ac1-e39a9318e052.png)

Calculating style of predictions
Downloading (…)olve/main/vocab.json: 100% 798k/798k [00:00<00:00, 3.87MB/s]
Downloading (…)olve/main/merges.txt: 100% 456k/456k [00:00<00:00, 2.91MB/s]
Downloading (…)cial_tokens_map.json: 100% 239/239 [00:00<00:00, 89.4kB/s]
Downloading (…)okenizer_config.json: 100% 25.0/25.0 [00:00<00:00, 9.22kB/s]
Downloading (…)lve/main/config.json: 100% 794/794 [00:00<00:00, 303kB/s]
Downloading pytorch_model.bin: 100% 501M/501M [00:07<00:00, 67.8MB/s]
Some weights of the model checkpoint at SkolkovoInstitute/roberta_toxicity_classifier were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
100% 1/1 [00:00<00:00,  1.87it/s]
Calculating BLEU similarity
Calculating similarity by Wieting subword-embedding SIM model
100% 1/1 [00:00<00:00, 35.24it/s]
Calculating CoLA acceptability stats
2023-03-30 14:13:04 | INFO | fairseq.file_utils | loading archive file models/cola
2023-03-30 14:13:04 | INFO | fairseq.file_utils | loading archive file models/cola/cola-bin
Traceback (most recent call last):
  File "/content/fairseq/metric.py", line 173, in <module>
    cola_stats = do_cola_eval(args, preds)
  File "/content/fairseq/metric.py", line 85, in do_cola_eval
    cola_roberta = RobertaModel.from_pretrained(
  File "/content/fairseq/fairseq/models/roberta/model.py", line 369, in from_pretrained
    x = hub_utils.from_pretrained(
  File "/content/fairseq/fairseq/hub_utils.py", line 82, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/content/fairseq/fairseq/checkpoint_utils.py", line 432, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/content/fairseq/fairseq/checkpoint_utils.py", line 350, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/content/fairseq/fairseq/checkpoint_utils.py", line 694, in _upgrade_state_dict
    state["cfg"] = convert_namespace_to_omegaconf(state["args"])
  File "/content/fairseq/fairseq/dataclass/utils.py", line 390, in convert_namespace_to_omegaconf
    overrides, deletes = override_module_args(args)
  File "/content/fairseq/fairseq/dataclass/utils.py", line 312, in override_module_args
    _override_attr(k, FairseqConfig.__dataclass_fields__[k].type, args)
  File "/content/fairseq/fairseq/dataclass/utils.py", line 264, in _override_attr
    val = list(map(t_args[0], val))
TypeError: 'NoneType' object is not iterable
 
(i've moved metric.py into fairseq folder, which i installed from github, as pip wasn't working, just to clear confusion)
I've loaded Cola model and all, but i don't understand what's the problem, please take a look @avidale , thank you 

here is the notebook for ref:  https://colab.research.google.com/drive/16r7DZxeVEsQu2daYiFpyfTUwFfvkTop2?usp=sharing

**Comment by avidale** [comment]
The problem seems to be somewhere in Fairseq, and I have no ideas what could be wrong with it. Maybe, you can try installing an older version of Fairseq.

**Comment by bhaveshk1502** [comment]
Also pip install fairseq wasn't working, i installed it via github. Any particular version of fairseq you suggest?

**Comment by bhaveshk1502** [comment]
tried with fairseq 0.10.0 , it worked.
